#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyproj>=3.7"]
# ///
"""Regenerate all.json from PROJ's proj.db.

Replaces the previous MapTiler-API-based updater. All metadata (name, bbox,
area, unit, deprecated) comes straight from proj.db; the wkt/proj4 exports and
the accuracy of the default transformation to WGS84 are generated by PROJ
itself via pyproj.

The database bundled with the pyproj wheel is usually far behind the EPSG
registry, so the newest proj.db that can be found on this machine is used
instead (see choose_database() and tools/fetch-proj-db.py).

Like the MapTiler exports, the wkt/proj4 strings are exports of the CRS
*bound to WGS84* with the transformation PROJ would pick by default, so they
include +towgs84=/+nadgrids= parameters where applicable.
"""

import json
import os
import sqlite3
import sys
import warnings
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

# Grid availability influences which transformation PROJ picks as the default.
# Enable network mode so all grids on cdn.proj.org count as available (must be
# set before pyproj is imported).
os.environ.setdefault('PROJ_NETWORK', 'ON')

import pyproj
from pyproj import CRS
from pyproj.crs import BoundCRS
from pyproj.database import get_database_metadata, query_crs_info
from pyproj.datadir import get_data_dir, set_data_dir
from pyproj.enums import WktVersion
from pyproj.transformer import TransformerGroup

ROOT = Path(__file__).resolve().parent.parent
OUT_FILE = ROOT / 'all.json'

# Extra places to look for a proj.db that is newer than the one pyproj bundles.
# The first entry is what tools/fetch-proj-db.py writes, the others pick up a
# PROJ installed system-wide.
EXTRA_DATA_DIRS = [
    ROOT / '.proj-data',
    Path('/usr/share/proj'),
    Path('/usr/local/share/proj'),
    Path('/opt/homebrew/share/proj'),
]

# PROJ emits plenty of "lossy conversion" warnings for to_proj4/WKT1 exports.
warnings.filterwarnings('ignore')


def database_info(data_dir: Path) -> tuple[tuple[int, ...], tuple[int, int]] | None:
    """Return ((EPSG version), (layout major, minor)) of data_dir's proj.db."""
    database = data_dir / 'proj.db'
    if not database.is_file():
        return None

    try:
        connection = sqlite3.connect(f'file:{database}?mode=ro', uri=True)
        try:
            metadata = dict(connection.execute('SELECT key, value FROM metadata').fetchall())
        finally:
            connection.close()
    except sqlite3.Error:
        return None

    epsg = tuple(int(part) for part in metadata.get('EPSG.VERSION', 'v0').lstrip('v').split('.') if part.isdigit())
    layout = (
        int(metadata.get('DATABASE.LAYOUT.VERSION.MAJOR', 0)),
        int(metadata.get('DATABASE.LAYOUT.VERSION.MINOR', 0)),
    )
    return epsg, layout


def bundled_data_dir() -> Path:
    """The data directory pyproj resolved on its own (the wheel's, usually)."""
    for entry in get_data_dir().split(os.pathsep):
        if (Path(entry) / 'proj.db').is_file():
            return Path(entry)
    sys.exit('pyproj has no usable proj.db')


def choose_database() -> None:
    """Switch pyproj to the newest proj.db available.

    An older PROJ library reads a newer database as long as the layout major
    version matches; a mismatch means the database was built for a PROJ that is
    too new for the installed library, so it is skipped.
    """
    best_dir = bundled_data_dir()
    bundled_info = database_info(best_dir)
    if bundled_info is None:
        sys.exit(f'{best_dir / "proj.db"} is not a PROJ database')
    best_epsg, (layout_major, _) = bundled_info

    candidates = [Path(entry) for entry in os.environ.get('PROJ_DATA', '').split(os.pathsep) if entry]
    candidates += EXTRA_DATA_DIRS

    for candidate in candidates:
        info = database_info(candidate)
        if info is None:
            continue
        epsg, layout = info
        if layout[0] != layout_major:
            print(f'Skipping {candidate}: database layout {layout[0]}.{layout[1]} needs a newer PROJ')
            continue
        if epsg > best_epsg:
            best_dir, best_epsg = candidate, epsg

    set_data_dir(str(best_dir))
    os.environ['PROJ_DATA'] = str(best_dir)


def init_worker(data_dir: str) -> None:
    set_data_dir(data_dir)


AXIS_ORIENTATION_MAP = {
    'east': 'e',
    'west': 'w',
    'north': 'n',
    'south': 's',
    'up': 'u',
    'down': 'd',
}
NON_AXIS_ORIENTATIONS = {'geocentricx', 'geocentricy', 'geocentricz', 'unspecified'}


def proj4_axis(axis_info) -> str | None:
    """Return a PROJ +axis value for an ordered sequence of CRS axes."""
    directions = [axis.direction.lower() for axis in axis_info]
    if len(directions) < 2 or any(direction in NON_AXIS_ORIENTATIONS for direction in directions):
        return None

    characters = []
    for direction in directions:
        for orientation, character in AXIS_ORIENTATION_MAP.items():
            if direction.startswith(orientation):
                characters.append(character)
                break
        else:
            return None

    if len(characters) > 3:
        return None
    return ''.join(characters + ['u'] * (3 - len(characters)))


def with_axis(proj4: str | None, axis_info) -> str | None:
    if proj4 is None or '+axis=' in proj4:
        return proj4

    axis = proj4_axis(axis_info)
    if axis is None:
        return proj4
    return proj4.replace(' +type=crs', f' +axis={axis} +type=crs')


def bound_to_wgs84(crs: CRS, transformers) -> CRS:
    """Bind ``crs`` to WGS84 using PROJ's default transformation (mimics
    proj_crs_create_bound_crs_to_WGS84). Returns ``crs`` unchanged if no
    suitable transformation exists."""
    for transformer in transformers:
        # For concatenated operations the WGS84-transformation is one of the
        # steps; single-step transformers are the transformation themselves.
        for op in [*transformer.operations, transformer]:
            try:
                bound = BoundCRS(
                    source_crs=crs.to_json_dict(),
                    target_crs='EPSG:4326',
                    transformation=op.to_json_dict(),
                )
                proj4 = bound.to_proj4()
                if proj4 and ('+towgs84=' in proj4 or '+nadgrids=' in proj4):
                    return bound
            except Exception:
                pass
        break  # only consider the default (first) transformer
    return crs


def build_entry(item: tuple[int, str, bool]) -> dict:
    code, name, deprecated = item
    crs = CRS.from_authority('EPSG', code)

    # Accuracy of the transformation PROJ would pick by default to WGS84
    # (negative accuracy means "unknown").
    accuracy = None
    transformers = []
    try:
        transformers = TransformerGroup(crs, 'EPSG:4326', allow_ballpark=False).transformers
        if transformers and transformers[0].accuracy >= 0:
            accuracy = transformers[0].accuracy
    except Exception:
        pass

    export_crs = bound_to_wgs84(crs, transformers)

    wkt = None
    try:
        wkt = export_crs.to_wkt(WktVersion.WKT1_GDAL)
    except Exception:
        pass

    proj4 = None
    try:
        proj4 = with_axis(export_crs.to_proj4(), crs.axis_info)
    except Exception:
        pass

    bbox = None
    area = None
    if crs.area_of_use is not None:
        aou = crs.area_of_use
        bbox = [aou.west, aou.south, aou.east, aou.north]
        area = aou.name

    unit = crs.axis_info[0].unit_name if crs.axis_info else None

    return {
        'code': code,
        'name': name,
        'wkt': wkt,
        'proj4': proj4,
        'bbox': bbox,
        'unit': unit,
        'area': area,
        'accuracy': accuracy,
        'deprecated': bool(deprecated),
    }


def main() -> None:
    choose_database()
    print(
        f'PROJ {pyproj.proj_version_str}, '
        f'EPSG dataset {get_database_metadata("EPSG.VERSION")} ({get_database_metadata("EPSG.DATE")}) '
        f'from {get_data_dir()}'
    )

    # CRSs with multiple usage extents are returned once per extent — dedupe.
    infos = sorted(
        {int(i.code): (int(i.code), i.name, i.deprecated) for i in query_crs_info(auth_name='EPSG', allow_deprecated=True)}.values(),
        key=lambda i: i[0],
    )
    print(f'Found {len(infos)} EPSG CRS definitions in proj.db')

    entries = []
    with ProcessPoolExecutor(initializer=init_worker, initargs=(get_data_dir(),)) as pool:
        for i, entry in enumerate(pool.map(build_entry, infos, chunksize=64), 1):
            entries.append(entry)
            if i % 1000 == 0 or i == len(infos):
                print(f'Processed {i} out of {len(infos)}')

    OUT_FILE.write_text(json.dumps(entries, indent=4, ensure_ascii=False), encoding='utf-8')
    print(f'Wrote {OUT_FILE}')


if __name__ == '__main__':
    sys.exit(main())
