name: Check Grids

on:
    workflow_dispatch:
    push:
        paths:
            - 'all.json'
            - 'grids/**'
        branches:
            - '**'
    pull_request:
        branches:
            - main

permissions:
    contents: read # to fetch code (actions/checkout)

jobs:
    check-grids:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Check if all referenced grids are present in this package
              run: npm run-script check-grids
